#!/bin/bash

DEFAULTLOG=/root/CHANGELOG

if [ -z "$DEFAULTLOG" -a -z "$1" ] ; then
	echo "usage $0 <CHANGELOG FILE> [\"comment\"]"
	exit 1
elif [ -n "$DEFAULTLOG"  ] ; then
  changelog=$DEFAULTLOG
else
  changelog="$1"
  shift
fi

if [ ! -f "$changelog" ] ; then
	echo "can not access file $changelog"
	exit 1
fi

comment="$*"

if [ "$comment" = "" ] ; then
	echo "Enter a 1 line comment.  Press enter when done."
	echo -n "C: "
	read C
	comment="$C"
fi

D=$(date +%Y.%m.%d-%H:%M:%S)
echo "Added to $changelog: "
echo "$D $comment" | tee -a $changelog
