#!/usr/bin/env ruby

require 'pp'

@net172_octet_rejects = [nil, %w(16 20 24 31), %w(0 1)]


def generate_net172(n=:C)
  begin
    octet_2 = (rand(16) + 16).to_s
  end while @net172_octet_rejects[1].include?(octet_2)

  return "172.#{octet_2}" if n == :B

  begin
  octet_3 = rand(256).to_s
  end while @net172_octet_rejects[2].include?(octet_3)

  "172.#{octet_2}.#{octet_3}"
end


printf "Rejects are: "
pp @net172_octet_rejects

puts "Class B: #{generate_net172 :B}"

puts "Class C: #{generate_net172 :C}"

