#!/bin/bash

system=`uname -s`

me=$(basename $0)

[[ "$me" = "toggle-lockscreen" ]] && action="toggle"
[[ -n "$1" ]] && action="$1"

# TODO: add prefererred lock app

function app-available() {
  if which $1 > /dev/null 2>&1 ; then
    true
  else
    false
  fi
}

if [ "$system" = "Darwin" ] ; then
  check_askforpassword_host="-currentHost read com.apple.screensaver askForPassword"
  check_askforpassword="read com.apple.screensaver askForPassword"
  origstate=$(defaults $check_askforpassword_host 2> /dev/null  || defaults $check_askforpassword 2> /dev/null )

  toggle_askforpassword 1 > /dev/null 2>&1
  osascript -e 'activate application "ScreenSaverEngine"'

  if [ ! "$1" = "-q" ] ; then
    echo -n "Press ENTER "
    read
    toggle_askforpassword $origstate > /dev/null 2>&1
  fi
elif [ "$system" = "Linux" ] ; then
  case $action in
    toggle)
      xautolock -toggle
      exit 0
      ;;
    enable)
      xautolock -enable
      exit 0
      ;;
    disable)
      xautolock -disable
      exit 0
      ;;
  esac

  #fixme: check for xscreensaver/gnome
  LOCKERS="xscreensaver-command slimlock gnome-screensaver-command xtrlock slock"
  for l in $LOCKERS ; do
    if app-available $l ; then
      locker=$l
      break
    else
      echo "Locker application $l not found"
      #exit 1
    fi
  done

  case $locker in
    xscreensaver-command)
      xscreensaver-command -lock ; exit 0 ;;
    slimlock)
      slimlock ; exit 0 ;;
    gnome-screensaver-command)
      gnome-screensaver-command -a -l ; exit 0 ;;
    xtrlock)
      xtrlock ; exit 0 ;;
    slock)
      slock ; exit 0 ;;
    *)
      echo "unknown locker application"
      exit 1 ;;
  esac
else
  echo "not implemented for your system ($system) yet"
fi
