#!/bin/bash

# Usage: rotate-screen [absolute] [action]
#
# ACTIONS:
#   flip|invert - invert the screen from the current rotation
#   left        - rotate to the left
#   right       - rotate to the right
#
# OPTION:
#   absolute - this forces the rotation to be relative to "normal" rotation vs current

default_output="LVDS1"
default_rotation="normal"

read -a foo <<< $(xrandr -q |grep " connected" |head -n 1| awk '{print $1" "$4}')
output=${foo[0]}
cr=${foo[1]}

case $cr in
  l|left) current_rotation="left" ;;
  r|right) current_rotation="right" ;;
  i|inverted) current_rotation="inverted" ;;
  *) current_rotation="normal" ;;
esac

me=$(basename $0)

if [ "$me" = "flip-screen" -a -z "$1" ] ; then
  action="flip"
else
  action="$1"
fi

# Act like we are in normal mode so the switch will go to the default rotation
if [ "$action" = "absolute" ] ; then
  current_rotation=normal
fi


case $action in
flip|inverted|invert)
  case $current_rotation in
    left) rotation="right" ;;
    right) rotation="left" ;;
    normal) rotation="inverted" ;;
    inverted) rotation="normal" ;;
    *) rotation="normal" ;;
  esac
  ;;
upsidedown|forfriend|look|up)
  rotation="inverted"
  ;;
left)
  case $current_rotation in
    left) rotation="inverted" ;;
    inverted) rotation="right" ;;
    right) rotation="normal" ;;
    *) rotation="left" ;;
  esac
  ;;
right)
  case $current_rotation in
    right) rotation="inverted" ;;
    inverted) rotation="left" ;;
    left) rotation="normal" ;;
    *) rotation="right" ;;
  esac
  ;;
*)
  rotation="normal"
  ;;
esac


xrandr --output "$output" --rotate "$rotation"
