#!/bin/bash

which xscreensaver > /dev/null
if [ $? = 0 ] ; then
  pidof xscreensaver > /dev/null 2>&1
  if [ ! $? = 0 ] ; then
    nohup xscreensaver -no-splash > /dev/null 2>&1 &
    disown
  fi
else
  echo 'no screensaver found!'
  exit 1
fi

xscreensaver-command -activate > /dev/null 2>&1
