#!/bin/sh

# $Id: $

key="$HOME/.ssh/id_rsa-4096-20080925.pub"

if [ ! -f "$key" ] ; then
	echo "key $key not found"
	exit 1
fi

echo "Uploading $key to $1"

#cat ~/.ssh/id_rsa.pub ~/.ssh/id_dsa-old.pub ~/.ssh/id_rsa-old.pub 2> /dev/null | ssh $* 'mkdir .ssh; chmod 700 .ssh; touch .ssh/authorized_keys; chmod 600 .ssh/authorized_keys; chmod go-w .; cat >> .ssh/authorized_keys'
cat $key 2> /dev/null | ssh $* 'mkdir -p .ssh; chmod 700 .ssh; touch .ssh/authorized_keys; ln -s ~/.ssh/authorized_keys ~/.ssh/authorized_keys2 2> /dev/null; chmod 600 .ssh/authorized_keys; chmod go-w .; cat >> .ssh/authorized_keys'
