#!/bin/bash

PYGMENTIZE="/opt/local/bin/pygmentize-2.7"

if [ ! -t 0 ];then
        file=/dev/stdin
elif [ -f $1 ];then
        file=$1
else
        echo "Usage: $0 code.c"
        echo "or e.g. head code.c|$0"
        exit 1
fi
$PYGMENTIZE -f terminal -g $file | less -r
