#!/bin/bash

if [ ! `uname -s` = "Darwin" ] ; then
  echo "This is an OS X (Darwin) only script"
  exit 255
fi

if [ ! "$1" = 0 -a ! "$1" = 1 -a ! "$1" = "" ] ; then
  echo "usage: $0 [0|1]"
  exit 255
elif [ "$1" = 0 ] ; then
  state=1
elif [ "$1" = 1 ] ; then
  state=0
else
  check_askforpassword_host="-currentHost read com.apple.screensaver askForPassword"
  check_askforpassword="read com.apple.screensaver askForPassword"
  state=$(defaults $check_askforpassword_host 2> /dev/null  || defaults $check_askforpassword 2> /dev/null )
fi

if [ "$state" = 0 ] ; then
  state=1
  msg="The screensaver password has been enabled"
  wake=true
else
  state=0
  msg="The screensaver password has been disabled"
  wake=false
fi

defaults write com.apple.screensaver askForPassword -int $state 2> /dev/null
defaults -currentHost write com.apple.screensaver askForPassword -int $state 2> /dev/null

read -r -d '' COMMAND <<EOC
tell application "System Events"
tell security preferences
set require password to wake to $wake
end tell
end tell
EOC

osascript -e "$COMMAND"

echo $msg
#exit $state
exit 0
