#!/bin/bash

synclient TouchpadOff=$(synclient -l | grep -c 'TouchpadOff.*=.*0')
exit $?

state=$(synclient -l |grep -i touch | awk -F"= " '{print $2}')
case $state in
  1) newstate=0 ;;
  0) newstate=1 ;;
esac

/usr/bin/synclient TouchpadOff=$newstate
